dist: focal
language: c

addons:
  apt_packages:
    - lib32z1
    - lib32stdc++6
    - p7zip-full
    - rsync

env:
  - SOURCEMOD=1.11

script:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash build.sh $SOURCEMOD ${TRAVIS_COMMIT::7}; fi'